def data_pack_item():

   
    list_packages_regulatory = [
        "AMP PLAS TRANSL",
        "AMP PLAS TRANS",
        "AMP VD AMB",
        "AMP VD TRANS",
        "APLIC PREENC PLAS OPC",
        "APLIC PREENC PLAS TRANS",
        "BG AL",
        "BG AL PLAS OPC",
        "BG PLAS AL OPC",
        "BG PLAS OPC",
        "BG PLAS TRANS",
        "BL AL AL",
        "BL AL PLAS AMB",
        "BL AL PLAS OPC",
        "BL AL PLAS TRANSL",
        "BL AL PLAS TRANS",
        "BOLS PLAS TRANS",
        "BOLS PLAS TRANS SIST FECH",
        "BOMBO PLAS OPC",
        "BOMBO PLAS TRANSL",
        "CAR VD TRANS",
        "CIL AL",
        "CIL MET",
        "ENV AL",
        "ENV AL/PAP",
        "ENV AL/PLAS",
        "ENV PAP",
        "ENV PLAS OPC",
        "EST PLAS",
        "FLAC PLAS AMB",
        "FLAC PLAS OPC",
        "FLAC PLAS TRANS",
        "FLAC VD TRANS",
        "FLAC VD AMB",
        "FLAC VD OPC",
        "FR AL",
        "FR PLAS AMB",
        "FR PLAS OPC",
        "FR PLAS TRANSL",
        "FR PLAS TRANS",
        "FR VD AMB",
        "FR VD OPC",
        "FR VD TRANS",
        "FA PLAS TRANS",
        "FA PLAS TRANS SIST FECH",
        "FA VD AMB",
        "FA VD TRANS",
        "FR APLIC PLAS AMB",
        "FR APLIC PLAS OPC",
        "FR APLIC PLAS TRANSL",
        "FR APLIC PLAS TRANS",
        "FR APLIC VD AMB",
        "FR APLIC VD OPC",
        "FR APLIC VD TRANS",
        "FR TRANSF VD AB",
        "FR TRANSF VD TRANS",
        "FR GOT PLAS AMB",
        "FR GOT PLAS OPC",
        "FR GOT PLAS TRANSL",
        "FR GOT PLAS TRANS",
        "FR GOT VD AMB",
        "FR GOT VD OPC",
        "FR GOT VD TRANS",
        "FR SPR PLAS AMB",
        "FR SPR PLAS OPC",
        "FR SPR PLAS TRANSL",
        "FR SPR PLAS TRANS",
        "FR SPR VD AMB",
        "FR SPR VD OPC",
        "FR SPR VD TRANS",
        "LAM AL",
        "LAM PAP",
        "PT MET",
        "PT PLAS AMB",
        "PT PLAS OPC",
        "PT PLAS TRANSL",
        "PT PLAS TRANS",
        "PT VD AMB",
        "PT VD OPC",
        "PT VD TRANS",
        "SER PREENC PLAS AMB",
        "SER PREENC PLAS TRANS",
        "SER PREENC VD AMB",
        "SER PREENC VD TRANS",
        "STR AL",
        "STR AL/PAP",
        "STR AL/PLAS",
        "STR PAP",
        "STR PLAS OPC",
        "TB AL",
        "TB PLAS"
    ]

    # Create a list of the first word in each string
    first_parck_name = []
    for i in list_packages_regulatory:
        first_parck_name.append(i.split()[0])

    # Remove duplicates by converting to a set and back to a list
    first_parck_name = list(set(first_parck_name))

    return first_parck_name

